config/routes.rb
Rails.application.routes.draw do

  resources :blog_posts
  resources :comments, only: [:edit, :create, :update, :destroy]

  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :comments

	validates :title, :author, :blog_entry, presence: true ##Attriutes ...presence :true ...if you pass a 0 zero trough program it will give error
	validates :title, uniqueness: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog_post

  validates :author, :comment_entry, :blog_post_id, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	before_action :set_blog_post, only: [:show, :edit, :update, :destroy]


  def index
  	@blog_posts = BlogPost.all 
  end

  def new
  	@blog_post = BlogPost.new
  end

  def edit
    # @blog_post = BlogPost.find(params[:id])  ### in the top already before action
  end

  def show
    @comment = Comment.new
  	
  end

  def create
  	@blog_post = BlogPost.new(blog_post_params) ###Model class
  	
  	respond_to do |format|
  		if @blog_post.save
  			format.html {redirect_to @blog_post, notice: "blog post was created succesfully."}
  		else
  			format.html {render :new}

  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @blog_post.update(blog_post_params)
  			format.html {redirect_to @blog_post, notice: "blog post wat updated succesfully."}
  		else
  			format.html {render :edit}
  		end
    end
  end

def destroy
	@blog_post.destroy
	respond_to do |format|
		format.html {redirect_to blog_posts_url, notice: "Your blog post was DESTROYED!!!"}
	end
end	

private 

	def blog_post_params
		params.require(:blog_post).permit(:title, :author, :blog_entry)
	end 

	def set_blog_post
		@blog_post = BlogPost.find(params[:id])  ##use primary key..needs to by unique
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
  end


  def create
  	@comment = Comment.new(comment_params) ###Model class
  	
  	respond_to do |format|
  		if @comment.save
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was created succesfully."}
  		else
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment failed to past."}
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @comment.update(comment_params)
  			format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Comment was updated succesfully."}
  		else
  			format.html {render :edit}
  		end
  end
end

def destroy
	@blog_post.destroy
	respond_to do |format|
		format.html {redirect_to blog_post_path(id: @comment.blog_post_id), notice: "Your blog post was DESTROYED!!!"}
	end
end

private 

def comment_params
	params.require(:comment).permit(:author, :comment_entry, :blog_post_id)
 
end

def set_comment
	@comment = Comment.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
	<%= form_for(@blog_post) do |f| %>
	<% if @blog_post.errors.any? %>
		<div class="error_explanation">
			<h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post form being saved:</h2>

			<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

		<div class="panel panel-default">
			<div class="panel-heading">

				<div class="formgroup">
					<%= f.text_field :title, class: "form-control", placeholder: "Enter your cool blog post name here..." %>
				</div>
				
				<div class="formgroup">
					<%= f.text_field :author, class: 'form-control', placeholder: "Enter your name" %>

				</div>
			</div>

			<div class="panel-body">
				<div class="formgroup">
					<%= f.text_area :blog_entry, class: 'form-control', rows: "12", placeholder: "Start typing away..." %>

				</div>
			</div>
		</div>

	<div class="actions">
		<%= f.submit "Post", class: "btn btn-default" %>
	</div>
	
	<% end %>
	

app/views/blog_posts/edit.html.erb
<div class="row">
<div class="col-lg-6 col-lg-offset-3">

<h1>Editing Blog Post</h1>
</div>

<div class="col-lg-6 col-lg-offset-3 container">

<%= render "form" %>


<br>
<%= link_to 'Back', blog_post_path(@blog_post), class: "btn btn-default" %>   <!-- ###@blog_post because of method before_action -->
<%= link_to 'Home', blog_posts_path, class: "btn btn-default" %>

</div>
</div>

app/views/blog_posts/index.html.erb
<div class="row">

<div class="col-lg-6 col-lg-offset-3">
<h1>My Personal Blog</h1>




	<% @blog_posts.each do |blog_post| %>  <!-- ###all blog posts selected to print out -->	

			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="heading">
						<%= blog_post.title  %>  <!-- #no @add because from the block -->
					</div>
				</div>
			
				<div class="panel-body">
					<div class="author">
						by <%= blog_post.author %><br />
					</div>

						<p><%= blog_post.blog_entry %></p>
						<a href="blog">Continue</a>"

						<p><strong>created at:</strong> <%= blog_post.created_at %></p>
				</div>

			<div class="panel-footer">
				<%= link_to 'Show', blog_post, class: "btn btn-primary" %>  <!-- ### no path because you have to perform specific instance like show and detroy -->
				<%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %> <!--  ###(blog_post) .. ID blog post... -->
				<%= link_to 'Destroy', blog_post, method: :delete,	data: {confirm: 'Are you sure?' }, class: "btn btn-danger" %>			<!-- ###linked to GET ...There is no destroy page like Edit...so we need to use a method Delete -->
			</div>
 
		</div>

	<% end %>

<br />
<%= link_to 'New Blog Post', new_blog_post_path, class: "btn btn-default" %>
</div>
</div>


<!-- truncate("Once upon a time in a world far far away") { link_to "Continue", "#" }
# => "Once upon a time in a wo...<a href="#">Continue</a>" -->

app/views/blog_posts/new.html.erb
<div class="row">
<div class="col-lg-6 col-lg-offset-3 text-center">
<h1>Create a New Blog Post</h1>
</div>

<div class="col-lg-6 col-lg-offset-3 container">
	
<%= render "form" %> 



</div>
</div>
<br>
<div class="col-lg-6 col-lg-offset-3">
<%= link_to "Back", blog_posts_path, class: "btn btn-default" %>
</div>

app/views/blog_posts/show.html.erb
<div class="row">

<div class="col-lg-6 col-lg-offset-3">


<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>
	<div class="panel-body">
		<p>by <%= @blog_post.author %></p>
		<p><%= @blog_post.blog_entry %></p>
	</div>	
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		Comments
	</div>
	<div class="panel-body">
		 <%= render @comment %> <!-- ###"comments/comment" also ok ...comment partial to show comments -->
	</div>
</div>

<div class="panel panel-success">
	<div class="panel-heading">
		Make a comment
	</div>
	<div class="panel-body">
		<%= render 'comments/form' %>
		<!-- # only form if its in the same folder what you want to render -->
	</div>
</div>


 <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "btn btn-default" %>  |
 <%= link_to 'Back', blog_posts_path, class: "btn btn-default"%>
</div>
</div>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>

	<h4><%= comment.author %></h4>

	<p><%= comment.comment_entry %></p>

	
<% end %>

<%= link_to 'Edit', edit_comment_path, class: "btn btn-default" %>

app/views/comments/_form.html.erb
	<%= form_for(@comment) do |f| %>  <!-- ##controller -> def show @comment  -->
	<% if @comment.errors.any? %>
		<div class="error_explanation">
			<h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post form being saved:</h2>

			<ul>
			<% @comment.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>


	<div class="form-group">
		<%= f.text_field :author, class: "form-control", placeholder: "Your Name" %>
	</div>

	<div class="form-group">
		<%= f.text_area :comment_entry, class: "form-control", rows:"3", placeholder: "Enter comment here.." %>
	</div>

	<div class="form-group hidden">
		<%= f.number_field :blog_post_id, value: @blog_post.id %>
	
	</div>

	<div class="action"> 
	<%= f.submit "Comment", class: "btn btn-default" %>

	</div>

	<% end %>

app/views/comments/edit.html.erb
<!-- <h1>Editing Comment</h1>

<div class="container">

<%= render "form" %>

</div>


<%= link_to 'Back', @edit_blog_post, class: "btn btn-default" %>   <!-- ###@blog_post because of method before_action -->
<%= link_to 'Home', blog_posts_path, class: "btn btn-default" %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustBuildIT</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>